import type { ClayBody } from "@/types";

// Cone-to-Celsius approximate conversion table used for min/max temps
// Cone -06 ≈ 999°C, Cone -02 ≈ 1063°C, Cone 1 ≈ 1137°C, Cone 6 ≈ 1222°C,
// Cone 10 ≈ 1305°C, Cone 12 ≈ 1335°C

export const CLAY_BODIES: ClayBody[] = [
  // ── Stoneware ──────────────────────────────────────────────────────────────
  {
    id: "white-stoneware",
    name: "White Stoneware",
    type: "stoneware",
    shrinkageRate: 12,
    firingTempMin: 1222,
    firingTempMax: 1240,
    coneMin: 6,
    coneMax: 6,
    plasticity: 0.75,
    grogContent: 0.05,
    color: "#e8ddd0",
    firedColor: "#d6c9b8",
    description:
      "A versatile, mid-fire white stoneware ideal for functional ware. Smooth texture with moderate plasticity. Fires to a warm off-white in oxidation. Excellent for wheel throwing and handbuilding.",
    properties: {
      vitrification: true,
      waterAbsorption: 0.5,
      thermalShock: "moderate",
      recommendedUse: "functional, decorative",
    },
  },
  {
    id: "iron-stoneware",
    name: "Iron Stoneware",
    type: "stoneware",
    shrinkageRate: 11,
    firingTempMin: 1222,
    firingTempMax: 1305,
    coneMin: 6,
    coneMax: 10,
    plasticity: 0.7,
    grogContent: 0.08,
    color: "#b5936b",
    firedColor: "#7a5c40",
    description:
      "Iron-rich stoneware body that fires to warm brown tones. Excellent for reduction firing where iron produces dramatic flashing effects. Well-suited for rustic functional ware and sculptural pieces.",
    properties: {
      vitrification: true,
      waterAbsorption: 1.0,
      thermalShock: "moderate",
      recommendedUse: "functional, sculptural",
    },
  },
  {
    id: "raku-stoneware",
    name: "Raku Stoneware",
    type: "raku",
    shrinkageRate: 8,
    firingTempMin: 999,
    firingTempMax: 1137,
    coneMin: -6,
    coneMax: 1,
    plasticity: 0.65,
    grogContent: 0.2,
    color: "#d4bfa0",
    firedColor: "#8c7055",
    description:
      "Open-body stoneware with high grog content designed to withstand the thermal shock of raku firing. The grog allows rapid heat absorption and cooling without cracking. Porous body is ideal for raku glaze effects.",
    properties: {
      vitrification: false,
      waterAbsorption: 15,
      thermalShock: "high resistance",
      recommendedUse: "raku, decorative",
    },
  },
  {
    id: "sculpture-grog-stoneware",
    name: "Sculpture Grog Stoneware",
    type: "stoneware",
    shrinkageRate: 9,
    firingTempMin: 1222,
    firingTempMax: 1240,
    coneMin: 6,
    coneMax: 6,
    plasticity: 0.5,
    grogContent: 0.4,
    color: "#c4a882",
    firedColor: "#9a7a5a",
    description:
      "Heavy-grog stoneware formulated for large-scale sculpture. The high grog content (40%) dramatically reduces shrinkage and warping, making it ideal for thick-walled vessels and sculptural forms over 30 cm.",
    properties: {
      vitrification: true,
      waterAbsorption: 2.0,
      thermalShock: "high resistance",
      recommendedUse: "sculpture, large forms",
    },
  },
  {
    id: "black-clay-stoneware",
    name: "Black Clay Stoneware",
    type: "stoneware",
    shrinkageRate: 11,
    firingTempMin: 1222,
    firingTempMax: 1305,
    coneMin: 6,
    coneMax: 10,
    plasticity: 0.7,
    grogContent: 0.06,
    color: "#3a3028",
    firedColor: "#2a2018",
    description:
      "Iron and manganese-rich black stoneware that fires to a deep charcoal-black. Creates dramatic contrast with light-colored glazes. Popular for both wheel-thrown and sculptural work.",
    properties: {
      vitrification: true,
      waterAbsorption: 0.8,
      thermalShock: "moderate",
      recommendedUse: "functional, decorative, sculptural",
    },
  },
  {
    id: "paper-clay-stoneware",
    name: "Paper Clay Stoneware",
    type: "paper_clay",
    shrinkageRate: 10,
    firingTempMin: 1222,
    firingTempMax: 1240,
    coneMin: 6,
    coneMax: 6,
    plasticity: 0.8,
    grogContent: 0.02,
    color: "#ddd3c4",
    firedColor: "#c8b89a",
    description:
      "Stoneware with added cellulose fiber (paper pulp) that dramatically increases workability and green strength. Pieces can be joined wet-to-dry without cracking. Fiber burns out in bisque firing. Ideal for thin, complex forms.",
    properties: {
      vitrification: true,
      waterAbsorption: 0.6,
      thermalShock: "moderate",
      fiberContent: "6%",
      recommendedUse: "sculptural, thin-walled, complex assemblages",
    },
  },
  {
    id: "porcelain-paper-mix",
    name: "Porcelain/Paper Mix",
    type: "paper_clay",
    shrinkageRate: 12,
    firingTempMin: 1222,
    firingTempMax: 1305,
    coneMin: 6,
    coneMax: 10,
    plasticity: 0.82,
    grogContent: 0.01,
    color: "#f2ede6",
    firedColor: "#e8e0d5",
    description:
      "Translucent porcelain base with paper fiber addition. Combines the whiteness and translucency of porcelain with the increased workability of paperclay. Excellent for lampshades, thin sculptural tiles, and intricate forms.",
    properties: {
      vitrification: true,
      waterAbsorption: 0.3,
      thermalShock: "low resistance",
      fiberContent: "4%",
      recommendedUse: "translucent sculpture, lampshades, tiles",
    },
  },

  // ── Porcelain ───────────────────────────────────────────────────────────────
  {
    id: "standard-porcelain",
    name: "Standard Porcelain",
    type: "porcelain",
    shrinkageRate: 14,
    firingTempMin: 1222,
    firingTempMax: 1305,
    coneMin: 6,
    coneMax: 10,
    plasticity: 0.6,
    grogContent: 0,
    color: "#f5f0e8",
    firedColor: "#ede8e0",
    description:
      "Classic cone 6–10 throwing porcelain. Bright white, vitreous, and slightly translucent when thin. Requires careful handling due to lower green strength. Excellent glaze fit with most commercial glazes.",
    properties: {
      vitrification: true,
      waterAbsorption: 0.1,
      thermalShock: "low resistance",
      recommendedUse: "wheel throwing, functional ware, tiles",
    },
  },
  {
    id: "bone-dry-porcelain",
    name: "Bone Dry Porcelain",
    type: "porcelain",
    shrinkageRate: 13.5,
    firingTempMin: 1222,
    firingTempMax: 1305,
    coneMin: 6,
    coneMax: 10,
    plasticity: 0.55,
    grogContent: 0,
    color: "#f8f4ee",
    firedColor: "#f0ece4",
    description:
      "Ultra-refined porcelain with very low plasticity. Must be dried very slowly to prevent cracking. Fires extremely white with virtually zero water absorption. Preferred for fine tableware and collectibles.",
    properties: {
      vitrification: true,
      waterAbsorption: 0.05,
      thermalShock: "very low resistance",
      recommendedUse: "fine tableware, slip casting",
    },
  },
  {
    id: "translucent-porcelain",
    name: "Translucent Porcelain",
    type: "porcelain",
    shrinkageRate: 15,
    firingTempMin: 1305,
    firingTempMax: 1335,
    coneMin: 10,
    coneMax: 10,
    plasticity: 0.45,
    grogContent: 0,
    color: "#faf8f4",
    firedColor: "#f4f0ea",
    description:
      "High-translucency porcelain for cone 10 reduction. When thrown thin (1–3 mm), transmits light beautifully. Challenging to throw due to very low plasticity — recommended for experienced throwers. Spectacular in reduction firing.",
    properties: {
      vitrification: true,
      waterAbsorption: 0.0,
      thermalShock: "very low resistance",
      translucency: "high",
      recommendedUse: "fine art, lampshades, teabowls",
    },
  },

  // ── Earthenware ─────────────────────────────────────────────────────────────
  {
    id: "red-earthenware",
    name: "Red Earthenware",
    type: "earthenware",
    shrinkageRate: 10,
    firingTempMin: 999,
    firingTempMax: 1063,
    coneMin: -6,
    coneMax: -2,
    plasticity: 0.85,
    grogContent: 0.03,
    color: "#c4613a",
    firedColor: "#a84a28",
    description:
      "High-iron low-fire earthenware. Very plastic and easy to throw. Rich red-orange color after firing. Not vitreous — glazing is essential for functional use. Common in traditional folk pottery and terracotta-style work.",
    properties: {
      vitrification: false,
      waterAbsorption: 12,
      thermalShock: "moderate",
      recommendedUse: "functional (glazed), decorative, tiles",
    },
  },
  {
    id: "white-earthenware",
    name: "White Earthenware",
    type: "earthenware",
    shrinkageRate: 9,
    firingTempMin: 999,
    firingTempMax: 1063,
    coneMin: -6,
    coneMax: -2,
    plasticity: 0.8,
    grogContent: 0.02,
    color: "#ede8dc",
    firedColor: "#e0d8cc",
    description:
      "Low-fire white body. Fires to a clean cream-white suitable for bright, opaque glazes and underglaze decoration. Very common in commercial studio pottery. Excellent surface for detailed painted decoration.",
    properties: {
      vitrification: false,
      waterAbsorption: 10,
      thermalShock: "moderate",
      recommendedUse: "functional (glazed), decorative, majolica",
    },
  },
  {
    id: "terracotta",
    name: "Terracotta",
    type: "terracotta",
    shrinkageRate: 8,
    firingTempMin: 999,
    firingTempMax: 1100,
    coneMin: -6,
    coneMax: 2,
    plasticity: 0.9,
    grogContent: 0.05,
    color: "#c85c35",
    firedColor: "#b04520",
    description:
      "Traditional Mediterranean-style terracotta body. Warm red-orange after firing. High plasticity makes it ideal for hand-built garden pottery, pots, and tiles. Accepts both low- and mid-fire glazes with good adhesion.",
    properties: {
      vitrification: false,
      waterAbsorption: 14,
      thermalShock: "moderate",
      recommendedUse: "garden pots, tiles, architectural ceramics",
    },
  },

  // ── Air-Dry ─────────────────────────────────────────────────────────────────
  {
    id: "air-dry-white",
    name: "Air-Dry White",
    type: "air_dry",
    shrinkageRate: 15,
    firingTempMin: 0,
    firingTempMax: 0,
    coneMin: 0,
    coneMax: 0,
    plasticity: 0.7,
    grogContent: 0,
    color: "#f8f5f0",
    firedColor: "#f0ece4",
    description:
      "White air-drying clay that hardens without kiln firing. Contains polymer binders that set at room temperature over 24–72 hours. Suitable for decorative pieces, educational use, and quick prototyping. Can be painted with acrylics.",
    properties: {
      vitrification: false,
      waterAbsorption: 25,
      thermalShock: "not applicable",
      dryingTime: "24-72 hours",
      recommendedUse: "decorative, educational, prototyping",
    },
  },
  {
    id: "air-dry-natural",
    name: "Air-Dry Natural",
    type: "air_dry",
    shrinkageRate: 13,
    firingTempMin: 0,
    firingTempMax: 0,
    coneMin: 0,
    coneMax: 0,
    plasticity: 0.72,
    grogContent: 0.04,
    color: "#d4b896",
    firedColor: "#c8aa88",
    description:
      "Natural-tone air-drying clay with earthy beige color. Slightly groggy texture mimics real stoneware aesthetics without firing. Ideal for rustic sculptural work and educational pottery projects. Finished pieces can be sealed with acrylic varnish.",
    properties: {
      vitrification: false,
      waterAbsorption: 22,
      thermalShock: "not applicable",
      dryingTime: "24-72 hours",
      recommendedUse: "decorative, sculpture, educational",
    },
  },

  // ── Polymer ─────────────────────────────────────────────────────────────────
  {
    id: "polymer-clay-white",
    name: "Polymer Clay White",
    type: "polymer",
    shrinkageRate: 1,
    firingTempMin: 130,
    firingTempMax: 135,
    coneMin: 0,
    coneMax: 0,
    plasticity: 0.9,
    grogContent: 0,
    color: "#fdfcfa",
    firedColor: "#f5f3ef",
    description:
      "PVC-based polymer clay that cures in a domestic oven at 130°C for 15–30 minutes. Virtually no shrinkage. Stays flexible and workable until cured. Excellent for jewelry, miniatures, and detailed sculptural work. Compatible with acrylic paints after curing.",
    properties: {
      vitrification: false,
      waterAbsorption: 0,
      thermalShock: "not applicable",
      ovenTemp: "130°C / 265°F",
      bakeTime: "15-30 minutes",
      recommendedUse: "jewelry, miniatures, sculpture",
    },
  },
  {
    id: "polymer-clay-translucent",
    name: "Polymer Clay Translucent",
    type: "polymer",
    shrinkageRate: 1,
    firingTempMin: 130,
    firingTempMax: 135,
    coneMin: 0,
    coneMax: 0,
    plasticity: 0.88,
    grogContent: 0,
    color: "#f0ede8",
    firedColor: "#e8e4dc",
    description:
      "Semi-translucent polymer clay for creating frosted glass effects, faux stone inlays, and layered color blending. Cures at 130°C. When cured thinly, allows light transmission for lamp and jewelry applications.",
    properties: {
      vitrification: false,
      waterAbsorption: 0,
      thermalShock: "not applicable",
      ovenTemp: "130°C / 265°F",
      bakeTime: "15-30 minutes",
      translucency: "semi",
      recommendedUse: "jewelry, faux stone, translucent effects",
    },
  },

  // ── Printable ───────────────────────────────────────────────────────────────
  {
    id: "3d-printable-ceramic",
    name: "3D Printable Ceramic",
    type: "printable",
    shrinkageRate: 13,
    firingTempMin: 1222,
    firingTempMax: 1305,
    coneMin: 6,
    coneMax: 10,
    plasticity: 0.4,
    grogContent: 0.02,
    color: "#e8e2d8",
    firedColor: "#d8d0c4",
    description:
      "Ceramic paste formulated for extrusion-based 3D printing. Requires a debinding step (slow ramp to 600°C to burn out organic binders) before the main glaze fire. Shrinkage is uniform and predictable for digital fabrication workflows.",
    properties: {
      vitrification: true,
      waterAbsorption: 0.5,
      thermalShock: "moderate",
      debindingRequired: true,
      debindingTemp: "600°C",
      recommendedUse: "digital fabrication, architectural ceramics, custom molds",
    },
  },
];
