import type { GlazeRecipe } from "@/types";

export const GLAZE_LIBRARY: GlazeRecipe[] = [
  // ── Mid-Fire Oxidation (Cone 6) ─────────────────────────────────────────────
  {
    id: "satin-white",
    name: "Satin White",
    colorHex: "#f5f0e8",
    surface: "satin",
    effects: ["none"],
    specificGravity: 1.46,
    coneMin: 6,
    coneMax: 6,
    compatibleAtmospheres: ["oxidation", "neutral"],
    ingredients: [
      { material: "Custer Feldspar", percentage: 25 },
      { material: "Whiting", percentage: 20 },
      { material: "EPK Kaolin", percentage: 15 },
      { material: "Silica (325 mesh)", percentage: 30 },
      { material: "Zinc Oxide", percentage: 5 },
      { material: "Zircopax", percentage: 5 },
    ],
    notes:
      "Reliable satin white with a soft, buttery surface. Works well over textures. Slight warm tone. Good base for colorant additions.",
    isPublic: true,
  },
  {
    id: "glossy-clear",
    name: "Glossy Clear",
    colorHex: "#eae5dc",
    surface: "glossy",
    effects: ["none"],
    specificGravity: 1.44,
    coneMin: 6,
    coneMax: 6,
    compatibleAtmospheres: ["oxidation", "neutral"],
    ingredients: [
      { material: "Custer Feldspar", percentage: 27 },
      { material: "Whiting", percentage: 21 },
      { material: "EPK Kaolin", percentage: 10 },
      { material: "Silica (325 mesh)", percentage: 35 },
      { material: "Dolomite", percentage: 7 },
    ],
    notes:
      "Crystal-clear gloss glaze that shows the clay body through it. Excellent over underglaze decoration. Minimal colorant response—add stains for color washes.",
    isPublic: true,
  },
  {
    id: "matte-black",
    name: "Matte Black",
    colorHex: "#1c1a18",
    surface: "matte",
    effects: ["none"],
    specificGravity: 1.5,
    coneMin: 6,
    coneMax: 6,
    compatibleAtmospheres: ["oxidation", "neutral"],
    ingredients: [
      { material: "Custer Feldspar", percentage: 30 },
      { material: "Whiting", percentage: 15 },
      { material: "EPK Kaolin", percentage: 18 },
      { material: "Silica (325 mesh)", percentage: 17 },
      { material: "Black Iron Oxide", percentage: 8 },
      { material: "Cobalt Carbonate", percentage: 2 },
      { material: "Manganese Dioxide", percentage: 10 },
    ],
    notes:
      "Deep, non-reflective black. Rich surface that absorbs light. Avoid overfiring — can turn glossy above cone 6. Pairs beautifully with satin white.",
    isPublic: true,
  },
  {
    id: "celadon-blue-green",
    name: "Celadon Blue-Green",
    colorHex: "#88b0a0",
    surface: "glossy",
    effects: ["breaking"],
    specificGravity: 1.45,
    coneMin: 6,
    coneMax: 6,
    compatibleAtmospheres: ["reduction", "oxidation"],
    ingredients: [
      { material: "Custer Feldspar", percentage: 40 },
      { material: "Whiting", percentage: 20 },
      { material: "EPK Kaolin", percentage: 14 },
      { material: "Silica (325 mesh)", percentage: 24 },
      { material: "Iron Oxide (red)", percentage: 1.5 },
      { material: "Cobalt Carbonate", percentage: 0.5 },
    ],
    notes:
      "Classic celadon. Fires pale grey-green in oxidation, richer teal-blue in reduction. Beautiful breaking over texture. Traditional Song dynasty aesthetic.",
    isPublic: true,
  },
  {
    id: "satin-sage-green",
    name: "Satin Sage Green",
    colorHex: "#7a9a80",
    surface: "satin",
    effects: ["none"],
    specificGravity: 1.47,
    coneMin: 6,
    coneMax: 6,
    compatibleAtmospheres: ["oxidation", "neutral"],
    ingredients: [
      { material: "Custer Feldspar", percentage: 25 },
      { material: "Whiting", percentage: 20 },
      { material: "Dolomite", percentage: 8 },
      { material: "EPK Kaolin", percentage: 12 },
      { material: "Silica (325 mesh)", percentage: 28 },
      { material: "Chrome Oxide", percentage: 2 },
      { material: "Iron Oxide (red)", percentage: 2 },
      { material: "Zircopax", percentage: 3 },
    ],
    notes:
      "Soft sage green with earthy undertones. Consistent in oxidation. Good food-safe surface when properly fired.",
    isPublic: true,
  },
  {
    id: "rust-orange",
    name: "Rust Orange",
    colorHex: "#c0622a",
    surface: "satin",
    effects: ["breaking"],
    specificGravity: 1.48,
    coneMin: 6,
    coneMax: 6,
    compatibleAtmospheres: ["oxidation", "neutral"],
    ingredients: [
      { material: "Custer Feldspar", percentage: 25 },
      { material: "Whiting", percentage: 18 },
      { material: "EPK Kaolin", percentage: 12 },
      { material: "Silica (325 mesh)", percentage: 25 },
      { material: "Red Iron Oxide", percentage: 12 },
      { material: "Rutile", percentage: 5 },
      { material: "Titanium Dioxide", percentage: 3 },
    ],
    notes:
      "Warm rust-orange with subtle variation. Iron and rutile create surface movement and breaking over texture. Richer on dark clay bodies.",
    isPublic: true,
  },
  {
    id: "cobalt-blue-glossy",
    name: "Cobalt Blue Glossy",
    colorHex: "#2a4fa8",
    surface: "glossy",
    effects: ["none"],
    specificGravity: 1.44,
    coneMin: 6,
    coneMax: 6,
    compatibleAtmospheres: ["oxidation", "neutral", "reduction"],
    ingredients: [
      { material: "Custer Feldspar", percentage: 27 },
      { material: "Whiting", percentage: 21 },
      { material: "EPK Kaolin", percentage: 10 },
      { material: "Silica (325 mesh)", percentage: 35 },
      { material: "Cobalt Carbonate", percentage: 2 },
      { material: "Dolomite", percentage: 5 },
    ],
    notes:
      "Rich royal blue high-gloss glaze. Very reliable in oxidation. Slightly deeper in reduction. Works on all white and light clay bodies.",
    isPublic: true,
  },
  {
    id: "lavender-matte",
    name: "Lavender Matte",
    colorHex: "#9888c0",
    surface: "matte",
    effects: ["none"],
    specificGravity: 1.46,
    coneMin: 6,
    coneMax: 6,
    compatibleAtmospheres: ["oxidation", "neutral"],
    ingredients: [
      { material: "Custer Feldspar", percentage: 25 },
      { material: "Whiting", percentage: 20 },
      { material: "EPK Kaolin", percentage: 18 },
      { material: "Silica (325 mesh)", percentage: 22 },
      { material: "Cobalt Carbonate", percentage: 1 },
      { material: "Manganese Dioxide", percentage: 3 },
      { material: "Zircopax", percentage: 8 },
      { material: "Titanium Dioxide", percentage: 3 },
    ],
    notes:
      "Soft, dusty lavender. Matte surface with slight depth. Reliable in oxidation. Avoid use in reduction (manganese can produce undesirable effects in some kilns).",
    isPublic: true,
  },

  // ── High-Fire Reduction (Cone 10) ───────────────────────────────────────────
  {
    id: "iron-red",
    name: "Iron Red (Hare's Fur)",
    colorHex: "#8a2018",
    surface: "glossy",
    effects: ["breaking", "reduction_spots"],
    specificGravity: 1.5,
    coneMin: 10,
    coneMax: 10,
    compatibleAtmospheres: ["reduction"],
    ingredients: [
      { material: "Potash Feldspar", percentage: 45 },
      { material: "Whiting", percentage: 10 },
      { material: "Silica (325 mesh)", percentage: 28 },
      { material: "EPK Kaolin", percentage: 10 },
      { material: "Red Iron Oxide", percentage: 7 },
    ],
    notes:
      "Classic iron red/hare's fur glaze in reduction. Heavy iron creates streaked, metallic-red surface with brown breaking over texture. Prone to running — apply thin on lower third of piece.",
    isPublic: true,
  },
  {
    id: "shino",
    name: "Shino",
    colorHex: "#e8d8c0",
    surface: "textured",
    effects: ["breaking", "ash", "reduction_spots"],
    specificGravity: 1.48,
    coneMin: 10,
    coneMax: 10,
    compatibleAtmospheres: ["reduction", "wood"],
    ingredients: [
      { material: "Nepheline Syenite", percentage: 60 },
      { material: "EPK Kaolin", percentage: 25 },
      { material: "Soda Ash", percentage: 10 },
      { material: "Silica (200 mesh)", percentage: 5 },
    ],
    notes:
      "Classic American Shino. Fires milky white-orange with carbon trapping. Creates dramatic orange flash in reduction with toasty, textured surface. Apply thick (3–5 mm) for best effects. Absorbs carbon beautifully.",
    isPublic: true,
  },
  {
    id: "temmoku",
    name: "Temmoku",
    colorHex: "#1a1008",
    surface: "glossy",
    effects: ["breaking", "running"],
    specificGravity: 1.52,
    coneMin: 10,
    coneMax: 10,
    compatibleAtmospheres: ["reduction", "neutral"],
    ingredients: [
      { material: "Potash Feldspar", percentage: 40 },
      { material: "Silica (325 mesh)", percentage: 25 },
      { material: "Whiting", percentage: 15 },
      { material: "EPK Kaolin", percentage: 5 },
      { material: "Red Iron Oxide", percentage: 10 },
      { material: "Bone Ash", percentage: 5 },
    ],
    notes:
      "Deep iron-saturate glaze firing black-brown with glossy surface. Classic Jian ware aesthetic. Can produce oil-spot or hare's fur effects in heavy reduction. Must have catch bowl beneath — runs significantly.",
    isPublic: true,
  },
  {
    id: "ash-glaze",
    name: "Ash Glaze",
    colorHex: "#9aae90",
    surface: "satin",
    effects: ["breaking", "ash", "running"],
    specificGravity: 1.44,
    coneMin: 10,
    coneMax: 12,
    compatibleAtmospheres: ["reduction", "wood", "soda"],
    ingredients: [
      { material: "Wood Ash (washed)", percentage: 45 },
      { material: "Potash Feldspar", percentage: 35 },
      { material: "EPK Kaolin", percentage: 10 },
      { material: "Silica (325 mesh)", percentage: 10 },
    ],
    notes:
      "Traditional wood ash glaze with natural variation from batch to batch. Fires green-grey with breaking over texture. Surface movement depends on kiln atmosphere. Apply medium-thick. Beautiful on textured surfaces.",
    isPublic: true,
  },
  {
    id: "crystalline-clear",
    name: "Crystalline Clear",
    colorHex: "#d8e8f0",
    surface: "crystalline",
    effects: ["crystallization"],
    specificGravity: 1.42,
    coneMin: 10,
    coneMax: 10,
    compatibleAtmospheres: ["oxidation", "neutral"],
    ingredients: [
      { material: "Ferro Frit 3110", percentage: 40 },
      { material: "Silica (200 mesh)", percentage: 25 },
      { material: "Zinc Oxide", percentage: 25 },
      { material: "EPK Kaolin", percentage: 5 },
      { material: "Titanium Dioxide", percentage: 5 },
    ],
    notes:
      "Zinc-silicate crystalline glaze. Crystals form during controlled cooling. Requires a special firing schedule with holds at 1050°C and slow cooling (30°C/hour) to 900°C. Must use catch bowl. No alumina in recipe allows large crystal growth.",
    isPublic: true,
  },

  // ── Low-Fire / Raku ─────────────────────────────────────────────────────────
  {
    id: "copper-green",
    name: "Copper Green",
    colorHex: "#3a8860",
    surface: "glossy",
    effects: ["none"],
    specificGravity: 1.44,
    coneMin: -6,
    coneMax: -1,
    compatibleAtmospheres: ["oxidation", "neutral"],
    ingredients: [
      { material: "Ferro Frit 3195", percentage: 80 },
      { material: "EPK Kaolin", percentage: 10 },
      { material: "Copper Carbonate", percentage: 5 },
      { material: "Silica (325 mesh)", percentage: 5 },
    ],
    notes:
      "Brilliant emerald green low-fire glaze. Copper fires green in oxidation, red/pink in reduction. Excellent gloss. Food safe when properly fired. Use with earthenware or white stoneware at low fire.",
    isPublic: true,
  },
  {
    id: "raku-metallic-bronze",
    name: "Raku Metallic Bronze",
    colorHex: "#7a5c28",
    surface: "metallic",
    effects: ["reduction_spots"],
    specificGravity: 1.45,
    coneMin: -6,
    coneMax: 1,
    compatibleAtmospheres: ["reduction", "saggar", "pit"],
    ingredients: [
      { material: "Ferro Frit 3134", percentage: 60 },
      { material: "Gerstley Borate", percentage: 15 },
      { material: "EPK Kaolin", percentage: 10 },
      { material: "Red Iron Oxide", percentage: 8 },
      { material: "Manganese Dioxide", percentage: 5 },
      { material: "Cobalt Carbonate", percentage: 2 },
    ],
    notes:
      "Post-fire reduction raku glaze creating bronze/copper metallic luster. Reduction smoke blackens unglazed areas. Not food safe. Apply medium thickness. Dramatic results with propane reduction in metal garbage can.",
    isPublic: true,
  },
  {
    id: "crater-volcanic",
    name: "Crater / Volcanic",
    colorHex: "#5a4838",
    surface: "textured",
    effects: ["none"],
    specificGravity: 1.52,
    coneMin: -6,
    coneMax: 6,
    compatibleAtmospheres: ["oxidation", "neutral"],
    ingredients: [
      { material: "Ferro Frit 3195", percentage: 40 },
      { material: "Custer Feldspar", percentage: 20 },
      { material: "Silica (325 mesh)", percentage: 15 },
      { material: "EPK Kaolin", percentage: 10 },
      { material: "Silicon Carbide (200 mesh)", percentage: 8 },
      { material: "Iron Oxide", percentage: 5 },
      { material: "Manganese Dioxide", percentage: 2 },
    ],
    notes:
      "Silicon carbide causes outgassing during firing, creating crater/lava surface texture. Results vary dramatically with thickness and firing speed. Exciting, unpredictable surface. Not food safe.",
    isPublic: true,
  },
  {
    id: "terracotta-slip",
    name: "Terracotta Slip",
    colorHex: "#b8522a",
    surface: "matte",
    effects: ["none"],
    specificGravity: 1.38,
    coneMin: -6,
    coneMax: 6,
    compatibleAtmospheres: ["oxidation", "reduction", "neutral"],
    ingredients: [
      { material: "Red Earthenware Clay", percentage: 55 },
      { material: "Silica (325 mesh)", percentage: 20 },
      { material: "Feldspar", percentage: 15 },
      { material: "Red Iron Oxide", percentage: 10 },
    ],
    notes:
      "Iron-rich slip for surface decoration. Apply at leather-hard stage. Burnishes to a warm red-orange sheen. Burns to soft matte terracotta surface. Used in traditional Southwestern and African pottery styles.",
    isPublic: true,
  },

  // ── Underglazes ─────────────────────────────────────────────────────────────
  {
    id: "underglaze-red",
    name: "Underglaze Red",
    colorHex: "#c82020",
    surface: "matte",
    effects: ["none"],
    specificGravity: 1.3,
    coneMin: -6,
    coneMax: 6,
    compatibleAtmospheres: ["oxidation", "neutral"],
    ingredients: [
      { material: "Commercial Underglaze Base", percentage: 75 },
      { material: "Red Ceramic Stain (Zirconium Inclusion)", percentage: 25 },
    ],
    notes:
      "Bright red underglaze for detailed decoration. Apply to greenware or bisque, cover with clear overglaze. Color stable from cone 06 to cone 6 in oxidation. Layer for intensity.",
    isPublic: true,
  },
  {
    id: "underglaze-blue",
    name: "Underglaze Blue",
    colorHex: "#1e3c9a",
    surface: "matte",
    effects: ["none"],
    specificGravity: 1.3,
    coneMin: -6,
    coneMax: 10,
    compatibleAtmospheres: ["oxidation", "neutral", "reduction"],
    ingredients: [
      { material: "Commercial Underglaze Base", percentage: 80 },
      { material: "Cobalt Stain", percentage: 20 },
    ],
    notes:
      "Classic cobalt blue underglaze. Fires consistently across a wide cone range. Slight intensification in reduction. Traditional blue-and-white porcelain technique.",
    isPublic: true,
  },
  {
    id: "underglaze-yellow",
    name: "Underglaze Yellow",
    colorHex: "#e8c030",
    surface: "matte",
    effects: ["none"],
    specificGravity: 1.3,
    coneMin: -6,
    coneMax: 6,
    compatibleAtmospheres: ["oxidation", "neutral"],
    ingredients: [
      { material: "Commercial Underglaze Base", percentage: 75 },
      { material: "Praseodymium Yellow Stain", percentage: 25 },
    ],
    notes:
      "Warm golden yellow underglaze. Stable in oxidation up to cone 6. Can fade at higher temperatures. Combine with clear overglaze for a bright yellow finish.",
    isPublic: true,
  },
  {
    id: "underglaze-black",
    name: "Underglaze Black",
    colorHex: "#181614",
    surface: "matte",
    effects: ["none"],
    specificGravity: 1.32,
    coneMin: -6,
    coneMax: 10,
    compatibleAtmospheres: ["oxidation", "neutral", "reduction"],
    ingredients: [
      { material: "Commercial Underglaze Base", percentage: 70 },
      { material: "Black Ceramic Stain (Spinel)", percentage: 30 },
    ],
    notes:
      "Dense, opaque black underglaze. Very stable across firing ranges. Excellent for fine line work, sgraffito reversal, and painting. Spinel-based stain does not burn out.",
    isPublic: true,
  },
  {
    id: "underglaze-white",
    name: "Underglaze White",
    colorHex: "#f8f5f0",
    surface: "matte",
    effects: ["none"],
    specificGravity: 1.35,
    coneMin: -6,
    coneMax: 6,
    compatibleAtmospheres: ["oxidation", "neutral"],
    ingredients: [
      { material: "Commercial Underglaze Base", percentage: 65 },
      { material: "Zircopax", percentage: 25 },
      { material: "Titanium Dioxide", percentage: 10 },
    ],
    notes:
      "Opaque white underglaze for reserve techniques on dark clay bodies. Creates crisp white under clear glaze. Can be used alone for a soft matte white surface.",
    isPublic: true,
  },

  // ── Specialty / Surface ─────────────────────────────────────────────────────
  {
    id: "terra-sigillata-burnish",
    name: "Terra Sigillata Burnish",
    colorHex: "#c06040",
    surface: "metallic",
    effects: ["none"],
    specificGravity: 1.15,
    coneMin: -6,
    coneMax: 2,
    compatibleAtmospheres: ["oxidation", "pit", "saggar"],
    ingredients: [
      { material: "Red Earthenware (deflocculated fine particles)", percentage: 90 },
      { material: "Sodium Silicate (deflocculant)", percentage: 1 },
      { material: "Water", percentage: 9 },
    ],
    notes:
      "Ancient Roman slip technique. Very fine clay particles settle, top fraction used. Apply at leather-hard stage, burnish with smooth stone or plastic. Fires to a silky sheen. Used in pit firing and saggar firing.",
    isPublic: true,
  },
  {
    id: "acrylic-wax-cold-finish",
    name: "Acrylic Wax Cold Finish",
    colorHex: "#c8b898",
    surface: "satin",
    effects: ["none"],
    specificGravity: 1.02,
    coneMin: 0,
    coneMax: 0,
    compatibleAtmospheres: ["oxidation"],
    ingredients: [
      { material: "Acrylic Polymer Emulsion", percentage: 80 },
      { material: "Carnauba Wax Emulsion", percentage: 15 },
      { material: "Water", percentage: 5 },
    ],
    notes:
      "Non-fired cold surface finish for air-dry clay, polymer clay, and bisque surfaces. Apply with soft brush or cloth. Provides satin sheen and water resistance. Not food safe. Can tint with acrylic pigments.",
    isPublic: true,
  },
];
