/**
 * PDF template generator for Clayverse.
 *
 * Since jsPDF is not installed, we generate a printable HTML page as a Blob
 * that can be opened in a new browser window and printed with window.print().
 * The page includes:
 *   - A scale ruler
 *   - The profile outline drawn as an SVG
 *   - Project information and dimensions
 *   - Optional grid overlay
 */

import { generateSVGProfile } from "./svgExporter";

export interface PDFTemplateParams {
  projectName: string;
  profile: [number, number][];
  dimensions: { width: number; height: number };
  scale: number;          // e.g. 1 (1:1), 0.5 (1:2), 0.2 (1:5)
  includeGrid: boolean;
  notes: string;
}

// ─── HTML template ────────────────────────────────────────────────────────────

function buildPrintHTML(params: PDFTemplateParams): string {
  const { projectName, profile, dimensions, scale, includeGrid, notes } = params;
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const scalePct = Math.round(scale * 100);
  const scaleLabel =
    scale === 1 ? "1:1" : scale === 0.5 ? "1:2" : scale === 0.2 ? "1:5" : `×${scalePct}%`;

  // Compute ruler length: 100 mm at current scale
  const rulerPx = 100 * scale * 3.7795; // 1 mm ≈ 3.7795 px at 96 dpi

  const svgContent = generateSVGProfile(profile, {
    scale: scale * 10,
    includeGrid,
    includeDimensions: true,
    color: "#a8683b",
  });

  const rulerSVG = `
    <svg width="${rulerPx.toFixed(0)}" height="30" xmlns="http://www.w3.org/2000/svg">
      <rect x="0" y="10" width="${rulerPx.toFixed(0)}" height="8" fill="none" stroke="#593424" stroke-width="1.5"/>
      ${Array.from({ length: 11 }, (_, i) => {
        const x = (i / 10) * rulerPx;
        const tickH = i % 5 === 0 ? 14 : 8;
        return `<line x1="${x.toFixed(1)}" y1="6" x2="${x.toFixed(1)}" y2="${(6 + tickH).toFixed(0)}" stroke="#593424" stroke-width="1"/>`;
      }).join("")}
      <text x="${(rulerPx / 2).toFixed(0)}" y="28" font-family="monospace" font-size="9" text-anchor="middle" fill="#593424">100 mm (at ${scaleLabel})</text>
    </svg>
  `;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>${projectName} — Clayverse Template</title>
  <style>
    @page {
      size: A4 portrait;
      margin: 15mm;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'Georgia', serif;
      color: #2f1a11;
      background: #fff;
      padding: 20px;
    }
    .header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      border-bottom: 2px solid #c0824a;
      padding-bottom: 10px;
      margin-bottom: 16px;
    }
    .header h1 {
      font-size: 22px;
      font-weight: 700;
      color: #593424;
    }
    .header .meta {
      font-size: 11px;
      color: #705e4a;
      text-align: right;
      line-height: 1.8;
    }
    .dimensions-bar {
      display: flex;
      gap: 24px;
      background: #fdf8f4;
      border: 1px solid #edd9c3;
      border-radius: 6px;
      padding: 10px 16px;
      margin-bottom: 14px;
      font-size: 12px;
    }
    .dim-item { display: flex; flex-direction: column; }
    .dim-label { font-size: 10px; color: #8a5130; text-transform: uppercase; letter-spacing: 0.06em; }
    .dim-value { font-size: 16px; font-weight: 700; color: #2f1a11; }
    .profile-area {
      border: 1px solid #d3c9b6;
      border-radius: 6px;
      padding: 10px;
      background: #fff;
      margin-bottom: 14px;
      display: flex;
      justify-content: center;
    }
    .profile-area svg { max-width: 100%; height: auto; }
    .ruler-section {
      margin-bottom: 14px;
      display: flex;
      align-items: center;
      gap: 12px;
    }
    .ruler-label { font-size: 11px; color: #705e4a; }
    .notes-section {
      border-top: 1px solid #edd9c3;
      padding-top: 12px;
    }
    .notes-section h3 { font-size: 13px; color: #8a5130; margin-bottom: 6px; }
    .notes-section p { font-size: 12px; line-height: 1.7; color: #40342b; white-space: pre-wrap; }
    .footer {
      margin-top: 20px;
      padding-top: 10px;
      border-top: 1px solid #edd9c3;
      font-size: 10px;
      color: #b9a98e;
      display: flex;
      justify-content: space-between;
    }
    @media print {
      body { padding: 0; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <h1>${projectName}</h1>
      <div style="font-size:12px;color:#8a5130;margin-top:4px;">Clay Profile Template</div>
    </div>
    <div class="meta">
      <div>Generated by Clayverse</div>
      <div>${date}</div>
      <div>Scale: ${scaleLabel}</div>
    </div>
  </div>

  <div class="dimensions-bar">
    <div class="dim-item">
      <span class="dim-label">Width</span>
      <span class="dim-value">${dimensions.width.toFixed(1)} mm</span>
    </div>
    <div class="dim-item">
      <span class="dim-label">Height</span>
      <span class="dim-value">${dimensions.height.toFixed(1)} mm</span>
    </div>
    <div class="dim-item">
      <span class="dim-label">Scale</span>
      <span class="dim-value">${scaleLabel}</span>
    </div>
    <div class="dim-item">
      <span class="dim-label">Profile Points</span>
      <span class="dim-value">${profile.length}</span>
    </div>
  </div>

  <div class="profile-area">
    ${svgContent}
  </div>

  <div class="ruler-section">
    <span class="ruler-label">Scale ruler:</span>
    ${rulerSVG}
  </div>

  ${notes ? `
  <div class="notes-section">
    <h3>Notes</h3>
    <p>${notes.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</p>
  </div>
  ` : ""}

  <div class="footer">
    <span>Clayverse — clayverse.app</span>
    <span>${projectName}</span>
  </div>

  <script>
    // Auto-trigger print dialog when opened in a new window
    window.addEventListener('load', function() {
      // Small delay to allow SVG rendering
      setTimeout(function() { window.print(); }, 500);
    });
  </script>
</body>
</html>`;
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Generate a printable HTML Blob for the given project template.
 * Open this Blob URL in a new window to trigger the print dialog.
 */
export function generatePDFTemplate(params: PDFTemplateParams): Blob {
  const html = buildPrintHTML(params);
  return new Blob([html], { type: "text/html;charset=utf-8" });
}

/**
 * Open the PDF template in a new window and trigger browser print.
 * Only works in browser environments.
 */
export function downloadPDF(blob: Blob, filename: string): void {
  if (typeof window === "undefined") return;

  const url = URL.createObjectURL(blob);
  const win = window.open(url, "_blank");
  if (!win) {
    // Fallback: download the HTML file if pop-ups are blocked
    const a = document.createElement("a");
    a.href = url;
    a.download = filename.endsWith(".html") ? filename : `${filename}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  }
  // Revoke after a delay to allow the new window to load
  setTimeout(() => URL.revokeObjectURL(url), 60_000);
}

// ─── Size estimate ────────────────────────────────────────────────────────────

export function estimatePDFSize(params: PDFTemplateParams): number {
  // HTML template is roughly 4 KB + ~100 bytes per profile point
  return 4096 + params.profile.length * 100;
}
